# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim
WORKDIR /app
# Install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
# Copy source
COPY . .
# Ensure Python outputs promptly
ENV PYTHONUNBUFFERED=1
# Default command
CMD ["python3", "main.py"]
